from __future__ import annotations

import json
from typing import Any, Callable

from industrial_gateway.models import BatchMessage


class PostgresSink:
    placeholder = "%s"
    dialect = "postgresql"

    def __init__(self, config: dict[str, Any], connect: Callable[[dict[str, Any]], Any] | None = None) -> None:
        self.config = config
        self._connect = connect or _connect_postgres
        self.connection: Any | None = None

    def start(self) -> None:
        self.connection = self._connect(self.config)
        if self.config.get("auto_create", True):
            self._execute(_create_table_sql(self.table_name, self.dialect))
            self.connection.commit()

    def stop(self) -> None:
        if self.connection is not None:
            self.connection.close()
            self.connection = None

    def publish_batch(self, message: BatchMessage) -> None:
        if self.connection is None:
            raise RuntimeError("database sink is not started")
        sql = _insert_sql(self.table_name, self.placeholder)
        for params in _params_from_message(message):
            self._execute(sql, params)
        self.connection.commit()

    @property
    def table_name(self) -> str:
        return _safe_table_name(self.config.get("table", "gateway_tag_values"))

    def _execute(self, sql: str, params: tuple[Any, ...] | None = None) -> None:
        cursor = self.connection.cursor()
        cursor.execute(sql, params) if params is not None else cursor.execute(sql)


class MssqlSink(PostgresSink):
    placeholder = "?"
    dialect = "mssql"

    def __init__(self, config: dict[str, Any], connect: Callable[[dict[str, Any]], Any] | None = None) -> None:
        super().__init__(config, connect or _connect_mssql)


def _connect_postgres(config: dict[str, Any]) -> Any:
    try:
        import psycopg
    except ImportError as exc:
        raise RuntimeError("psycopg is required for PostgreSQL sink") from exc
    return psycopg.connect(
        host=config.get("host", "localhost"),
        port=int(config.get("port", 5432)),
        dbname=config.get("database", "postgres"),
        user=config.get("username"),
        password=config.get("password"),
    )


def _connect_mssql(config: dict[str, Any]) -> Any:
    try:
        import pyodbc
    except ImportError as exc:
        raise RuntimeError("pyodbc is required for MSSQL sink") from exc
    connection_string = config.get("connection_string")
    if not connection_string:
        driver = config.get("driver", "ODBC Driver 18 for SQL Server")
        server = config.get("server", "localhost")
        port = int(config.get("port", 1433))
        database = config.get("database", "master")
        username = config.get("username", "")
        password = config.get("password", "")
        trust = "yes" if config.get("trust_server_certificate", True) else "no"
        connection_string = (
            f"DRIVER={{{driver}}};SERVER={server},{port};DATABASE={database};"
            f"UID={username};PWD={password};TrustServerCertificate={trust}"
        )
    return pyodbc.connect(connection_string)


def _create_table_sql(table: str, dialect: str) -> str:
    if dialect == "mssql":
        return f"""
        IF OBJECT_ID('{table}', 'U') IS NULL
        CREATE TABLE {table} (
            id BIGINT IDENTITY(1,1) PRIMARY KEY,
            device_id INT NULL,
            device_name NVARCHAR(255) NOT NULL,
            tag_name NVARCHAR(255) NOT NULL,
            tag_address INT NULL,
            value_json NVARCHAR(MAX) NULL,
            quality NVARCHAR(32) NOT NULL,
            error NVARCHAR(MAX) NULL,
            tag_timestamp NVARCHAR(64) NOT NULL,
            inserted_at DATETIME2 DEFAULT SYSUTCDATETIME()
        )
        """
    return f"""
    CREATE TABLE IF NOT EXISTS {table} (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        device_id INTEGER,
        device_name VARCHAR(255) NOT NULL,
        tag_name VARCHAR(255) NOT NULL,
        tag_address INTEGER,
        value_json TEXT,
        quality VARCHAR(32) NOT NULL,
        error TEXT,
        tag_timestamp VARCHAR(64) NOT NULL,
        inserted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """


def _insert_sql(table: str, placeholder: str) -> str:
    placeholders = ", ".join([placeholder] * 8)
    return (
        f"INSERT INTO {table} "
        "(device_id, device_name, tag_name, tag_address, value_json, quality, error, tag_timestamp) "
        f"VALUES ({placeholders})"
    )


def _params_from_message(message: BatchMessage) -> list[tuple[Any, ...]]:
    device = message.payload["device"]
    params = []
    for tag in message.payload["tags"]:
        params.append(
            (
                device.get("id"),
                device.get("name"),
                tag.get("name"),
                tag.get("address"),
                json.dumps(tag.get("value"), ensure_ascii=False),
                tag.get("quality"),
                tag.get("error"),
                tag.get("timestamp") or message.payload.get("timestamp"),
            )
        )
    return params


def _safe_table_name(value: str) -> str:
    if not value.replace("_", "").isalnum():
        raise ValueError("table name may only contain letters, numbers, and underscores")
    return value
